apiVersion: v1
kind: Service
metadata:
  name: {{ include "envars-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "envars-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook-api
  selector:
    {{- include "envars-webhook.selectorLabels" . | nindent 4 }}

# change