# deployment has a container that is allowed to receive env vars from node labels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: samples
  labels:
    app: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      initContainers:
        - name: prober
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "env"]
          envFrom:
            - configMapRef:
                name: env-configmap
      containers:
        - name: ingester
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "sleep infinity"]
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrets
          ports:
            - containerPort: 80
