apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
  namespace: samples
  labels:
    app: sample
spec:
  serviceName: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: prober
          image: busybox
          command: ["/bin/sh"]
          args: ["-c", "env"]
          envFrom:
            - configMapRef:
                name: env-configmap
      containers:
        - name: store-gateway
          image: k8s.gcr.io/nginx-slim:0.8
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrets
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
      volumes:
        - name: www
          emptyDir: {}
