name: Build and Publish

on:
  push:
    branches: [ "master", "build" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build webhook app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: Build
        run: CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o envars-webhook ./cmd/envars-webhook  
  
  image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Docker Hub and GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: |
            danfromtitan/envars-from-node-labels:latest 
            ghcr.io/danfromtitan/envars-from-node-labels:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}